version: "3.6"

services:
  backend-db:
    image: mariadb:${MARIADB_VERSION:-latest}
    container_name: backend-db
    env_file:
      - .env
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_USER=${MYSQL_USER:-root}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-wordpress}
    restart: always
