branch-defaults:
  groups:
    environment: Dongipclientgateway-env
environment-defaults:
  Dongipclientgateway-env:
    branch: groups
    repository: origin
global:
  application_name: dongip_client_gateway
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
