branch-defaults:
  main:
    environment: Dongipclientgateway-env
environment-defaults:
  Dongipclientgateway-env:
    branch: null
    repository: null
global:
  application_name: dongip-client-gateway
  default_ec2_keyname: aws-eb3
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
